<?php 

add_action('acf/init', 'avm_blocks_init');
function avm_blocks_init() {

    // Check function exists.
    if( function_exists('acf_register_block_type') ) {

        // Customizable super-block
        acf_register_block_type(array(
            'name'              => 'Customizable super-block',
            'title'             => __('Customizable super-block'),
            'description'       => __('A Customizable super-block.'),
            'render_template'   => 'blocks/customizable-super-block.php',
            'category'          => 'design',
        ));

        // CTA-puffar
        acf_register_block_type(array(
          'name'              => 'CTA-puffar',
          'title'             => __('CTA-puffar'),
          'description'       => __('CTA-puffar'),
          'render_template'   => 'blocks/cta-puffs.php',
          'category'          => 'design',
          'mode'              => 'edit',
          'supports' => array(
            'mode'     => false
          )
      ));
    }
}

// ACF Fields 
if( function_exists('acf_add_local_field_group') ):

  acf_add_local_field_group(array(
    'key' => 'group_6087fdd618993',
    'title' => 'CTA -puffar',
    'fields' => array(
      array(
        'key' => 'field_6088000568a5b',
        'label' => 'Typ av bakgrund',
        'name' => 'type-of-bg',
        'type' => 'radio',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'choices' => array(
          'none' => 'Ingen',
          'single-color' => 'Enfärgad',
          'image' => 'Bild',
        ),
        'allow_null' => 0,
        'other_choice' => 0,
        'default_value' => '',
        'layout' => 'vertical',
        'return_format' => 'value',
        'save_other_choice' => 0,
      ),
      array(
        'key' => 'field_6088005778cec',
        'label' => 'Bakgrundsfärg',
        'name' => 'background-color',
        'type' => 'color_picker',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
      ),
      array(
        'key' => 'field_6088007514280',
        'label' => 'Bakgrundsbild',
        'name' => 'background-image',
        'type' => 'image',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
        'preview_size' => 'medium',
        'library' => 'all',
        'min_width' => 0,
        'min_height' => 0,
        'min_size' => 0,
        'max_width' => 0,
        'max_height' => 0,
        'max_size' => 0,
        'mime_types' => '',
      ),
      array(
        'key' => 'field_608802b211b1c',
        'label' => 'Text-color',
        'name' => 'text-color',
        'type' => 'color_picker',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
      ),
      array(
        'key' => 'field_6087fde6e9a64',
        'label' => 'Puffar',
        'name' => 'puffs',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'collapsed' => '',
        'min' => 0,
        'max' => 0,
        'layout' => 'table',
        'button_label' => '',
        'sub_fields' => array(
          array(
            'key' => 'field_6087fe0ce9a65',
            'label' => 'Icon',
            'name' => 'icon',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'array',
            'preview_size' => 'medium',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
          ),
          array(
            'key' => 'field_6087fe1be9a66',
            'label' => 'Title',
            'name' => 'title',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_6087fe33e9a67',
            'label' => 'Paragraph',
            'name' => 'paragraph',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => '',
            'new_lines' => '',
          ),
        ),
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'block',
          'operator' => '==',
          'value' => 'acf/cta-puffar',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
  ));
  
  acf_add_local_field_group(array(
    'key' => 'group_60879e294b4ce',
    'title' => 'Customizable super-block (AVM)',
    'fields' => array(
      array(
        'key' => 'field_60879e7ae068d',
        'label' => 'Typ av bakgrund',
        'name' => 'type-of-bg',
        'type' => 'radio',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'choices' => array(
          'none' => 'Ingen',
          'single-color' => 'Enfärgad',
          'image' => 'Bild',
        ),
        'allow_null' => 0,
        'other_choice' => 0,
        'default_value' => '',
        'layout' => 'vertical',
        'return_format' => 'value',
        'save_other_choice' => 0,
      ),
      array(
        'key' => 'field_60879e3ce068c',
        'label' => 'Bakgrundsfärg',
        'name' => 'background-color',
        'type' => 'color_picker',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_60879e7ae068d',
              'operator' => '==',
              'value' => 'single-color',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
      ),
      array(
        'key' => 'field_60879ecda0af4',
        'label' => 'Bakgrundsbild',
        'name' => 'background-image',
        'type' => 'image',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_60879e7ae068d',
              'operator' => '==',
              'value' => 'image',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
        'preview_size' => 'medium',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
      ),
      array(
        'key' => 'field_6087d5c4b0e6e',
        'label' => 'Orientation',
        'name' => 'orientation',
        'type' => 'radio',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'choices' => array(
          'one-col' => 'En kolumn',
          'text-on-left' => 'Text on left side',
          'text-on-right' => 'Text on right side',
        ),
        'allow_null' => 0,
        'other_choice' => 0,
        'default_value' => '',
        'layout' => 'vertical',
        'return_format' => 'value',
        'save_other_choice' => 0,
      ),
      array(
        'key' => 'field_6087d8e22eaac',
        'label' => 'Text content',
        'name' => 'text-content',
        'type' => 'wysiwyg',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'full',
        'media_upload' => 1,
        'delay' => 0,
      ),
      array(
        'key' => 'field_6087f04dacc9d',
        'label' => 'Text-color',
        'name' => 'text-color',
        'type' => 'color_picker',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
      ),
      array(
        'key' => 'field_6087dbec830fc',
        'label' => 'Image content',
        'name' => 'img-content',
        'type' => 'image',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
        'preview_size' => 'medium',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
      ),
      array(
        'key' => 'field_6088ed448fa00',
        'label' => 'Bakgrundsbild positionering',
        'name' => 'background-image-pos',
        'type' => 'radio',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'choices' => array(
          'cover' => 'cover',
          'full-horizontally' => 'centrerad och täcker hela boxen horizontellt',
          'full-vertically' => 'centrerad och täcker hela boxen vertikalt',
          'top' => 'topställd',
          'left' => 'vänsterställd',
          'bottom' => 'mot botten',
          'right' => 'högerställd',
        ),
        'allow_null' => 0,
        'other_choice' => 0,
        'default_value' => '',
        'layout' => 'vertical',
        'return_format' => 'value',
        'save_other_choice' => 0,
      ),
      array(
        'key' => 'field_6087e547846f0',
        'label' => 'CTA - knapp-länk',
        'name' => 'cta-button-link',
        'type' => 'link',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
      ),
      array(
        'key' => 'field_6087e6a5c514c',
        'label' => 'CTA - knapp-länk text-färg',
        'name' => 'cta-button-link-color-text',
        'type' => 'color_picker',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
      ),
      array(
        'key' => 'field_6087e6d7cabbf',
        'label' => 'CTA - knapp-länk text-bakgrund',
        'name' => 'cta-button-link-color-bg',
        'type' => 'color_picker',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
      ),
      array(
        'key' => 'field_6087e6d4cabbe',
        'label' => 'CTA - knapp-länk border-hover-färg',
        'name' => 'cta-button-link-color-border-hover',
        'type' => 'color_picker',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
      )
    ),
    'location' => array(
      array(
        array(
          'param' => 'block',
          'operator' => '==',
          'value' => 'acf/customizable-super-block',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
  ));
  
  acf_add_local_field_group(array(
    'key' => 'group_6087d3039af24',
    'title' => 'Landingpage customization',
    'fields' => array(
      array(
        'key' => 'field_6087d30d15660',
        'label' => 'Background',
        'name' => 'background-color',
        'type' => 'color_picker',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
      ),
      array(
        'key' => 'field_6082d30d15361',
        'label' => 'Meny färg',
        'name' => 'landing-menu-color',
        'type' => 'color_picker',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
      ),
      array(
        'key' => 'field_6081d30d15462',
        'label' => 'Fetad länk',
        'name' => 'fat-menu-color',
        'type' => 'color_picker',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
      ),
      array(
        'key' => 'field_6081d20f15461',
        'label' => 'Fetad länk hover-färg',
        'name' => 'fat-menu-hover-color',
        'type' => 'color_picker',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
      ),
      array(
        'key' => 'field_608a3124bb8f8',
        'label' => 'Landing page special-menu',
        'name' => 'landing-menu',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'collapsed' => '',
        'min' => 0,
        'max' => 0,
        'layout' => 'table',
        'button_label' => '',
        'sub_fields' => array(
          array(
            'key' => 'field_608a339686807',
            'label' => 'Url',
            'name' => 'url',
            'type' => 'link',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'array',
          ),
          array(
            'key' => 'field_608a79ba94e93',
            'label' => 'Fet länk',
            'name' => 'fat',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => 0,
            'message' => '',
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
          ),
        ),
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_template',
          'operator' => '==',
          'value' => 'page-landing.php',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
  ));
  
endif;

?>
